message:
  source: "App1 initial value"

logging:
  level:
    ROOT: INFO

management.endpoints.web.exposure.include: '*'
spring:
  application:
    name: app1
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    bus:
      refresh:
        enabled: true
      enabled: true