
server:
  port: 8081

management.endpoints.web.exposure.include: '*'

message:
  source: "test"

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    bus:
      refresh:
        enabled: true
      enabled: true