server.port: 8888
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  profiles.active: native
  cloud:
    config:
      server:
        git.uri: "file:///Users/tomaszscibiorek/Projects/SpringCloudConfigTest/config/application.properties"
        native:
          search-locations:
            - "/Users/tomaszscibiorek/Projects/SpringCloudConfigTest/config/application.properties"
    bus:
      enabled: true
      refresh:
        enabled: true
  application:
    name: config-server

logging:
  level:
    ROOT: INFO
    org.springframework.cloud.config: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: busrefresh

